{{- if not .Values.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-printcost-secrets
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  SESSION_SECRET: {{ .Values.oidc.sessionSecret | quote }}
{{- end }}
